name: notification_repository
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_in_app_messaging: ^0.7.0+6
  firebase_messaging: ^14.1.1
  mankeli_core: ^0.0.2
  meta: any
  model:
    path: ../model

dev_dependencies:
  dart_code_metrics: any
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.0
  mocktail: any
  plugin_platform_interface: any
