name: authentication_repository
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.1.3
  firebase_core: any
  firebase_core_platform_interface: ^4.5.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  mankeli_core: ^0.0.2
  meta: ^1.8.0
  model:
    path: ../model

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: any
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.0
  mocktail: any
  plugin_platform_interface: any
