name: database_repository
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.1.0
  firebase_core: any
  flutter:
    sdk: flutter
  hive: ^2.2.3
  mankeli_core: ^0.0.2
  meta: ^1.8.0
  model:
    path: ../model
  path_provider: ^2.0.11

dev_dependencies:
  dart_code_metrics: any
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.0
  mocktail: any
  plugin_platform_interface: any
