name: tool
publish_to: none
description: A set of scripts to help speed up the development of the app

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cmd_plus: ^1.3.1
  path: ^1.8.3

dev_dependencies:
  dart_code_metrics: ^5.6.0
  mankeli_analysis: ^1.1.0
