name: permission_repository
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  mankeli_core: ^0.0.2
  meta: ^1.8.0
  permission_handler: any

dev_dependencies:
  dart_code_metrics: any
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.0
  mocktail: any
  plugin_platform_interface: any
